// Top-level build file where you can add configuration options common to all sub-projects/modules.
//file:noinspection GroovyAssignabilityCheck
//file:noinspection GrUnresolvedAccess
buildscript {
    // Defining versions in a single place
    ext {
        // sdk versions
        compile_sdk_version = 37
        build_tools_version = "37.0.0"
        min_sdk_version = 23
        target_sdk_version = 37
/* to check the latest version @see
https://play.google.com/console/u/0/developers/6867856033872987263/app/4975238491076611804/releases/overview
*/
        version_code = 25
        version_name = "2.2.5"
    }
    repositories {
    }
    dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.android.library apply false
    alias libs.plugins.kotlin.android apply false
    alias libs.plugins.google.services apply false
    alias libs.plugins.firebase.crashlytics apply false
    alias libs.plugins.firebase.perf apply false
}

subprojects {
    afterEvaluate {
        dependencies {
            // Add to avoid  w:Kotlin runtime JAR files in the classpath should have the same version
            implementation libs.kotlin.reflect

            // (Asynchronous programming) coroutines
            implementation libs.kotlinx.coroutines.core

            if (project.hasProperty('android')) {
                implementation libs.kotlinx.coroutines.android

                // Retrofit2
                implementation libs.retrofit
                implementation libs.converter.gson

//            Room Database
                //noinspection KaptUsageInsteadOfKsp
                kapt libs.room.compiler

                // Paging
                // Tried to upgrade to 3.3.6 and all versions between - does not compile.
                //noinspection GradleDependency
                implementation libs.paging.runtime

                /*  Bill of Materials for the Firebase platform.
                 * When using the BoM, no need to specify versions in Firebase library dependencies */
                implementation platform(libs.firebase.bom)

                // Declaring the dependencies for the Crashlytics and Analytics libraries
                implementation libs.firebase.crashlytics
                // Firebase SDK for Google Analytics
                implementation libs.firebase.analytics

                // avoids "Service not registered" exception
                implementation libs.play.services.basement
            }

            // Koin testing tools
            testImplementation libs.koin.test
            // Needed JUnit version
            testImplementation libs.koin.test.junit4

            testImplementation libs.truth
        }
    }
}

allprojects {
    repositories {
    }
}

ext {
    getParam = { key ->
        def value = System.getenv(key) ?: project.findProperty("env.$key")
        if (value) {
            println "$key = $value"
        }
        return value
    }

    HOST_URL = getParam("HOST_URL")
    COUNTRIES_API_KEY = getParam("COUNTRIES_API_KEY")
    DATABASE_NAME = getParam("DATABASE_NAME")

    SIGNING_KEY_DEBUG_PATH = getParam("SIGNING_KEY_DEBUG_PATH")
    SIGNING_KEY_DEBUG_PASSWORD = getParam("SIGNING_KEY_DEBUG_PASSWORD")
    SIGNING_KEY_DEBUG_KEY = getParam("SIGNING_KEY_DEBUG_KEY")
    SIGNING_KEY_DEBUG_KEY_PASSWORD = getParam("SIGNING_KEY_DEBUG_KEY_PASSWORD")

    SIGNING_KEY_RELEASE_PATH = getParam("SIGNING_KEY_RELEASE_PATH")
    SIGNING_KEY_RELEASE_PASSWORD = getParam("SIGNING_KEY_RELEASE_PASSWORD")
    SIGNING_KEY_RELEASE_KEY = getParam("SIGNING_KEY_RELEASE_KEY")
    SIGNING_KEY_RELEASE_KEY_PASSWORD = getParam("SIGNING_KEY_RELEASE_KEY_PASSWORD")
}

tasks.register('clean') {
    //noinspection GrDeprecatedAPIUsage
    delete rootProject.buildDir
}
