//file:noinspection GrUnresolvedAccess
plugins {
    alias libs.plugins.android.application
    alias libs.plugins.kotlin.android
    id 'kotlin-kapt'
    alias libs.plugins.google.services
    alias libs.plugins.firebase.crashlytics
    alias libs.plugins.firebase.perf
}

android {
    //noinspection GrDeprecatedAPIUsage
    compileSdkVersion libs.versions.compileSdk.get().toInteger()
    buildToolsVersion rootProject.build_tools_version

    //noinspection GroovyAssignabilityCheck
    defaultConfig {
        applicationId "ua.turskyi.travelling"
        minSdkVersion rootProject.min_sdk_version
        targetSdkVersion rootProject.target_sdk_version
        versionCode rootProject.version_code
        versionName rootProject.version_name

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        // to ensure that the translations of Firebase library are relevant to the application
        resourceConfigurations += ['en']
    }

    //noinspection GroovyAssignabilityCheck
    signingConfigs {
        production {
            storeFile file(rootProject.SIGNING_KEY_RELEASE_PATH)
            storePassword rootProject.SIGNING_KEY_RELEASE_PASSWORD
            keyAlias rootProject.SIGNING_KEY_RELEASE_KEY
            keyPassword rootProject.SIGNING_KEY_RELEASE_KEY_PASSWORD
        }
        dev {
            storeFile file(rootProject.SIGNING_KEY_DEBUG_PATH)
            storePassword rootProject.SIGNING_KEY_DEBUG_PASSWORD
            keyAlias rootProject.SIGNING_KEY_DEBUG_KEY
            keyPassword rootProject.SIGNING_KEY_DEBUG_KEY_PASSWORD
        }
    }

    //noinspection GroovyAssignabilityCheck
    buildTypes {
        //noinspection GroovyAssignabilityCheck
        release {
            minifyEnabled false
            //noinspection GroovyAssignabilityCheck
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
            signingConfig signingConfigs.production
            // used in manifest provider authorities
            resValue "string", "content_provider",
                    "com.facebook.app.FacebookContentProvider285452062466394"
        }
        debug {
            signingConfig signingConfigs.dev
// used in manifest provider authorities
            resValue "string", "content_provider",
                    "com.facebook.app.FacebookContentProvider285452062466394"
        }
    }

    //noinspection GroovyAssignabilityCheck
    buildFeatures {
        //noinspection GroovyAssignabilityCheck
        dataBinding true
        //noinspection GroovyAssignabilityCheck
        viewBinding true
        buildConfig = true
    }

    //noinspection GroovyAssignabilityCheck
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        //noinspection GrDeprecatedAPIUsage
        jvmTarget = "11"
    }

    testOptions.unitTests.includeAndroidResources = true
    namespace 'ua.turskyi.travelling'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(":domain")
    implementation project(':data')

    // kotlin
    api libs.kotlin.reflect

    // design components
    implementation libs.material

    implementation libs.fragment.ktx
    implementation libs.activity.ktx

    // android
    implementation libs.appcompat
    implementation libs.core.ktx

    // firebase
    implementation libs.firebase.messaging
    implementation(libs.firebase.perf) {
        // remove advertising dependency
        exclude module: "play-services-ads-identifier"
        exclude module: "play-services-measurement"
        exclude module: "play-services-measurement-sdk"
    }
    /* Declare the dependency for the Performance Monitoring library.
       When using the BoM, we don't specify versions in Firebase library dependencies. */
    implementation libs.firebase.analytics

    // ViewModel and LiveData
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.runtime.ktx
    implementation libs.lifecycle.extensions

    // Glide (Image caching and management)
    //noinspection KaptUsageInsteadOfKsp
    kapt libs.compiler
    implementation libs.glide

    // Displaying SVG images
    implementation libs.glidetovectoryou

    // BaseRecyclerViewAdapterHelper
    implementation libs.baserecyclerviewadapterhelper

    // Recyclerview
    implementation libs.recyclerview

    // CardView
    implementation libs.cardview

    // Android chart view / graph view library
    implementation libs.mpandroidchart

    // ViewPager2
    implementation libs.viewpager2

    // PhotoView
    implementation libs.photoview

    // Location
    implementation libs.play.services.location

    // Facebook SDK
    implementation libs.facebook.share
    implementation libs.facebook.applinks
    implementation libs.facebook.android.sdk

    // used for animation
    implementation libs.lottie

    // Koin for Android
    implementation(libs.koin.android)

    // Koin core features
    implementation(libs.koin.core)

    // tests
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    testImplementation libs.junit.jupiter.api
    testRuntimeOnly libs.junit.jupiter.engine

    // testImplementation for pure JVM unit tests
    testImplementation libs.kotlinx.coroutines.test

    // androidTestImplementation for Android instrumentation tests
    androidTestImplementation libs.kotlinx.coroutines.test
}
